site_name: 王也|买房手册
site_url: https://www.wudiguang.top
site_description: 收集&整理关于买房的信息
site_author: 王也

repo_url: https://github.com/mkdocs/mkdocs/
edit_uri: ""

theme:
    name: 'material'
    highlightjs: true
    hljs_languages:
        - yaml
        - django
    feature: 
        
      

nav:
    - 首页: index.md
    - 基本概念: 基本概念.md
    - 关于户型: 关于户型.md
    - 买房信息: 
      - 1.1.0 买房需要了解哪些信息: 1.1.0 买房需要了解哪些信息.md
      - 1.1.1 用地性质: 1.1.1 用地性质.md
      - 1.1.2 五证两书: 1.1.2 五证两书.md
      - 1.1.3 公摊面积: 1.1.3 公摊面积.md
      - 1.1.4 户型图: 1.1.4 户型图.md
      - 1.1.5 容积率和绿化率: 1.1.5 容积率和绿化率.md
      - 1.1.6 建筑面积: 1.1.6 建筑面积.md
      - 1.1.7 车位: 1.1.7 车位.md
      - 1.1.8 小产权房和大产权房: 1.1.8 小产权房和大产权房.md
      - 1.1.9 塔楼和板楼: 1.1.9 塔楼和板楼.md
      - 1.2.1 交房时出现面积误差怎么办: 1.2.1 交房时出现面积误差怎么办.md
      - 2.1.0 买房子准备工作: 2.1.0 买房子准备工作.md
      - 2.1.1 签约认购: 2.1.1 签约认购.md
      - 2.1.2 “定金”、“订金”、“认筹金”和“诚意金”: 2.1.2 “定金”、“订金”、“认筹金”和“诚意金”.md
      - 2.1.3 签购房合同该注意什么: 2.1.3 签购房合同该注意什么.md
      - 2.1.4 签合同后办这三件事: 2.1.4 签合同后办这三件事.md
      - 2.1.5 落户政策: 2.1.5 落户政策.md
      - 2.1.6 购房协议: 2.1.6 购房协议.md
      - 2.1.7 房屋产权年限: 2.1.7 房屋产权年限.md
      - 2.1.8 车位产权: 2.1.8 车位产权.md
      - 2.1.9 燃气初装费问题: 2.1.9 燃气初装费问题.md
      - 2.2.1 业主委员会: 2.2.1 业主委员会.md
      - 2.2.2 中华人民共和国物权法: 2.2.2 中华人民共和国物权法.md
      - 2.2.3 中华人民共和国物业管理条例: 2.2.3 中华人民共和国物业管理条例.md
      - 2.2.4 2018年物业管理条例修改: 2.2.4 2018年物业管理条例修改.md
      - 3.1.1贷款需要知道的有哪些: 3.1.1贷款需要知道的有哪些.md
      - 3.1.2 公积金贷款买房流程: 3.1.2 公积金贷款买房流程.md
      - 3.1.3 返乡贷款购房需要注意: 3.1.3 返乡贷款购房需要注意.md
      - 3.1.4 买房贷款审批: 3.1.4 买房贷款审批.md
      - 3.1.5 买房详细流程及贷款计算: 3.1.5 买房详细流程及贷款计算.md
      - 3.1.6 户籍地买房工作地提取公积金材料: 3.1.6 户籍地买房工作地提取公积金材料.md
      - 3.1.7 贷款担保人: 3.1.7 贷款担保人.md
      - 4.1.1验房注意有哪些: 4.1.1验房注意有哪些.md
      - 4.1.2 交房前必查: 4.1.2 交房前必查.md
      - 4.1.3 不动产登记: 4.1.3 不动产登记.md
      - 4.1.4不动产登记收费标准: 4.1.4不动产登记收费标准.md
      - 4.1.5 房产证办理: 4.1.5 房产证办理.md
      - 5.1.1 装修预算: 5.1.1 装修预算.md
      - 6.1.1 装修: 6.1.1 装修.md
      - 6.1.1.1 设计: 6.1.1.1 设计.md
      - 6.1.1.2 主体改造: 6.1.1.2 主体改造.md
      - 6.1.1.3 水电改造: 6.1.1.3 水电改造.md
      - 6.1.2 装修中用大砖还是用小砖: 6.1.2 装修中用大砖还是用小砖.md
      - 6.1.3 装修注意事项: 6.1.3 装修注意事项.md
      - 6.1.4 装修验收: 6.1.4 装修验收.md
      - 6.2.1 客厅装修效果图: 6.2.1 客厅装修效果图.md
      - 6.2.2 卧室装修效果图: 6.2.2 卧室装修效果图.md
      - 6.2.3 厨房装修效果图: 6.2.3 厨房装修效果图.md
      - 6.2.4 餐厅装修效果图: 6.2.4 餐厅装修效果图.md
      - 6.2.5 卫生间装修效果图: 6.2.5 卫生间装修效果图.md
    - 房地产数据查询: 房地产数据查询.md

extra_css:
    - css/extra.css

markdown_extensions:
    - toc:
        permalink: false
    - admonition
    - def_list


copyright: Copyright &copy; 2014 <a href="https://twitter.com/_tomchristie">Tom Christie</a>, Maintained by the <a href="/about/release-notes/#maintenance-team">MkDocs Team</a>.
google_analytics: ['UA-27795084-5', 'mkdocs.org']
